<?php

use Illuminate\Database\Seeder;

class SettingsSeeder extends Seeder
{
    public function run()
    {


        \DB::table('settings')->delete();

        \DB::table('settings')->insert(array (
            0 =>
                array (
                    'id' => 1,
                    'name' => 'about_ar',
                    'slug_ar' => 'من نحن باللغة العربية',
                    'slug_en' => 'About Us In Arabic',
                    'value' => 'وريم إيبسوم(Lorem Ipsum) هو ببساطة نص شكلي (بمعنى أن الغاية هي الشكل وليس المحتوى) ويُستخدم في صناعات المطابع ودور النشر. كان لوريم إيبسوم ولايزال المعيار للنص الشكلي منذ القرن الخامس عشر عندما قامت مطبعة مجهولة برص مجموعة من الأحرف بشكل عشوائي أخذتها من نص، لتكوّن كتيّب بمثابة دليل أو مرجع شكلي لهذه الأحرف. خمسة قرون من الزمن لم تقضي على هذا النص، بل انه حتى صار مستخدماً وبشكله الأصلي في الطباعة والتنضيد الإلكتروني. انتشر بشكل كبير في ستينيّات هذا القرن مع إصدار رقائق "ليتراسيت" (Letraset) البلاستيكية تحوي مقاطع من هذا النص، وعاد لينتشر مرة أخرى مؤخراَ مع ظهور برامج النشر الإلكتروني مثل "ألدوس بايج مايكر" (Aldus PageMaker) والتي حوت أيضاً على نسخ من نص لوريم إيبسوم.',
                    'input_type' => 2,
                    'category' => 1,
                    'created_at' => '2020-06-14 18:24:54',
                    'updated_at' => '2020-06-14 18:24:54',
                ),
            1 =>
                array (
                    'id' => 2,
                    'name' => 'about_en',
                    'slug_ar' => 'من نحن باللغة الانجليزية',
                    'slug_en' => 'About Us In English',
                    'value' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum',
                    'input_type' => 2,
                    'category' => 1,
                    'created_at' => '2020-06-14 18:24:54',
                    'updated_at' => '2020-06-14 18:24:54',
                ),
            2 =>
                array (
                    'id' => 3,
                    'name' => 'policy_ar',
                    'slug_ar' => 'الشروط والاحكام باللغة العربية',
                    'slug_en' => 'Terms And Conditions In Arabic',
                    'value' => 'وريم إيبسوم(Lorem Ipsum) هو ببساطة نص شكلي (بمعنى أن الغاية هي الشكل وليس المحتوى) ويُستخدم في صناعات المطابع ودور النشر. كان لوريم إيبسوم ولايزال المعيار للنص الشكلي منذ القرن الخامس عشر عندما قامت مطبعة مجهولة برص مجموعة من الأحرف بشكل عشوائي أخذتها من نص، لتكوّن كتيّب بمثابة دليل أو مرجع شكلي لهذه الأحرف. خمسة قرون من الزمن لم تقضي على هذا النص، بل انه حتى صار مستخدماً وبشكله الأصلي في الطباعة والتنضيد الإلكتروني. انتشر بشكل كبير في ستينيّات هذا القرن مع إصدار رقائق "ليتراسيت" (Letraset) البلاستيكية تحوي مقاطع من هذا النص، وعاد لينتشر مرة أخرى مؤخراَ مع ظهور برامج النشر الإلكتروني مثل "ألدوس بايج مايكر" (Aldus PageMaker) والتي حوت أيضاً على نسخ من نص لوريم إيبسوم.',
                    'input_type' => 2,
                    'category' => 1,
                    'created_at' => '2020-06-14 18:24:54',
                    'updated_at' => '2020-06-14 18:24:54',
                ),
            3 =>
                array (
                    'id' => 4,
                    'name' => 'policy_en',
                    'slug_ar' => 'الشروط والاحكام باللغة الانجليزية',
                    'slug_en' => 'Terms And Conditions In English',
                    'value' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum',
                    'input_type' => 2,
                    'category' => 1,
                    'created_at' => '2020-06-14 18:24:54',
                    'updated_at' => '2020-06-14 18:24:54',
                ),
            4 =>
                array (
                    'id' => 30,
                    'name' => 'about_ar',
                    'slug_ar' => 'من نحن باللغة العربية',
                    'slug_en' => 'About Us In Arabic',
                    'value' => 'وريم إيبسوم(Lorem Ipsum) هو ببساطة نص شكلي (بمعنى أن الغاية هي الشكل وليس المحتوى) ويُستخدم في صناعات المطابع ودور النشر. كان لوريم إيبسوم ولايزال المعيار للنص الشكلي منذ القرن الخامس عشر عندما قامت مطبعة مجهولة برص مجموعة من الأحرف بشكل عشوائي أخذتها من نص، لتكوّن كتيّب بمثابة دليل أو مرجع شكلي لهذه الأحرف. خمسة قرون من الزمن لم تقضي على هذا النص، بل انه حتى صار مستخدماً وبشكله الأصلي في الطباعة والتنضيد الإلكتروني. انتشر بشكل كبير في ستينيّات هذا القرن مع إصدار رقائق "ليتراسيت" (Letraset) البلاستيكية تحوي مقاطع من هذا النص، وعاد لينتشر مرة أخرى مؤخراَ مع ظهور برامج النشر الإلكتروني مثل "ألدوس بايج مايكر" (Aldus PageMaker) والتي حوت أيضاً على نسخ من نص لوريم إيبسوم.',
                    'input_type' => 2,
                    'category' => 1,
                    'created_at' => '2020-06-14 18:27:29',
                    'updated_at' => '2020-06-14 18:27:29',
                ),
            5 =>
                array (
                    'id' => 31,
                    'name' => 'about_en',
                    'slug_ar' => 'من نحن باللغة الانجليزية',
                    'slug_en' => 'About Us In English',
                    'value' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum',
                    'input_type' => 2,
                    'category' => 1,
                    'created_at' => '2020-06-14 18:27:29',
                    'updated_at' => '2020-06-14 18:27:29',
                ),
            6 =>
                array (
                    'id' => 32,
                    'name' => 'policy_ar',
                    'slug_ar' => 'الشروط والاحكام باللغة العربية',
                    'slug_en' => 'Terms And Conditions In Arabic',
                    'value' => 'وريم إيبسوم(Lorem Ipsum) هو ببساطة نص شكلي (بمعنى أن الغاية هي الشكل وليس المحتوى) ويُستخدم في صناعات المطابع ودور النشر. كان لوريم إيبسوم ولايزال المعيار للنص الشكلي منذ القرن الخامس عشر عندما قامت مطبعة مجهولة برص مجموعة من الأحرف بشكل عشوائي أخذتها من نص، لتكوّن كتيّب بمثابة دليل أو مرجع شكلي لهذه الأحرف. خمسة قرون من الزمن لم تقضي على هذا النص، بل انه حتى صار مستخدماً وبشكله الأصلي في الطباعة والتنضيد الإلكتروني. انتشر بشكل كبير في ستينيّات هذا القرن مع إصدار رقائق "ليتراسيت" (Letraset) البلاستيكية تحوي مقاطع من هذا النص، وعاد لينتشر مرة أخرى مؤخراَ مع ظهور برامج النشر الإلكتروني مثل "ألدوس بايج مايكر" (Aldus PageMaker) والتي حوت أيضاً على نسخ من نص لوريم إيبسوم.',
                    'input_type' => 2,
                    'category' => 1,
                    'created_at' => '2020-06-14 18:27:29',
                    'updated_at' => '2020-06-14 18:27:29',
                ),
            7 =>
                array (
                    'id' => 33,
                    'name' => 'policy_en',
                    'slug_ar' => 'الشروط والاحكام باللغة الانجليزية',
                    'slug_en' => 'Terms And Conditions In English',
                    'value' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum',
                    'input_type' => 2,
                    'category' => 1,
                    'created_at' => '2020-06-14 18:27:29',
                    'updated_at' => '2020-06-14 18:27:29',
                ),
            8 =>
                array (
                    'id' => 59,
                    'name' => 'about_ar',
                    'slug_ar' => 'من نحن باللغة العربية',
                    'slug_en' => 'About Us In Arabic',
                    'value' => 'وريم إيبسوم(Lorem Ipsum) هو ببساطة نص شكلي (بمعنى أن الغاية هي الشكل وليس المحتوى) ويُستخدم في صناعات المطابع ودور النشر. كان لوريم إيبسوم ولايزال المعيار للنص الشكلي منذ القرن الخامس عشر عندما قامت مطبعة مجهولة برص مجموعة من الأحرف بشكل عشوائي أخذتها من نص، لتكوّن كتيّب بمثابة دليل أو مرجع شكلي لهذه الأحرف. خمسة قرون من الزمن لم تقضي على هذا النص، بل انه حتى صار مستخدماً وبشكله الأصلي في الطباعة والتنضيد الإلكتروني. انتشر بشكل كبير في ستينيّات هذا القرن مع إصدار رقائق "ليتراسيت" (Letraset) البلاستيكية تحوي مقاطع من هذا النص، وعاد لينتشر مرة أخرى مؤخراَ مع ظهور برامج النشر الإلكتروني مثل "ألدوس بايج مايكر" (Aldus PageMaker) والتي حوت أيضاً على نسخ من نص لوريم إيبسوم.',
                    'input_type' => 2,
                    'category' => 1,
                    'created_at' => '2020-06-14 18:28:25',
                    'updated_at' => '2020-06-14 18:28:25',
                ),
            9 =>
                array (
                    'id' => 60,
                    'name' => 'about_en',
                    'slug_ar' => 'من نحن باللغة الانجليزية',
                    'slug_en' => 'About Us In English',
                    'value' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum',
                    'input_type' => 2,
                    'category' => 1,
                    'created_at' => '2020-06-14 18:28:25',
                    'updated_at' => '2020-06-14 18:28:25',
                ),
            10 =>
                array (
                    'id' => 61,
                    'name' => 'policy_ar',
                    'slug_ar' => 'الشروط والاحكام باللغة العربية',
                    'slug_en' => 'Terms And Conditions In Arabic',
                    'value' => 'وريم إيبسوم(Lorem Ipsum) هو ببساطة نص شكلي (بمعنى أن الغاية هي الشكل وليس المحتوى) ويُستخدم في صناعات المطابع ودور النشر. كان لوريم إيبسوم ولايزال المعيار للنص الشكلي منذ القرن الخامس عشر عندما قامت مطبعة مجهولة برص مجموعة من الأحرف بشكل عشوائي أخذتها من نص، لتكوّن كتيّب بمثابة دليل أو مرجع شكلي لهذه الأحرف. خمسة قرون من الزمن لم تقضي على هذا النص، بل انه حتى صار مستخدماً وبشكله الأصلي في الطباعة والتنضيد الإلكتروني. انتشر بشكل كبير في ستينيّات هذا القرن مع إصدار رقائق "ليتراسيت" (Letraset) البلاستيكية تحوي مقاطع من هذا النص، وعاد لينتشر مرة أخرى مؤخراَ مع ظهور برامج النشر الإلكتروني مثل "ألدوس بايج مايكر" (Aldus PageMaker) والتي حوت أيضاً على نسخ من نص لوريم إيبسوم.',
                    'input_type' => 2,
                    'category' => 1,
                    'created_at' => '2020-06-14 18:28:25',
                    'updated_at' => '2020-06-14 18:28:25',
                ),
            11 =>
                array (
                    'id' => 62,
                    'name' => 'policy_en',
                    'slug_ar' => 'الشروط والاحكام باللغة الانجليزية',
                    'slug_en' => 'Terms And Conditions In English',
                    'value' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum',
                    'input_type' => 2,
                    'category' => 1,
                    'created_at' => '2020-06-14 18:28:25',
                    'updated_at' => '2020-06-14 18:28:25',
                ),
            12 =>
                array (
                    'id' => 88,
                    'name' => 'about_ar',
                    'slug_ar' => 'من نحن باللغة العربية',
                    'slug_en' => 'About Us In Arabic',
                    'value' => 'وريم إيبسوم(Lorem Ipsum) هو ببساطة نص شكلي (بمعنى أن الغاية هي الشكل وليس المحتوى) ويُستخدم في صناعات المطابع ودور النشر. كان لوريم إيبسوم ولايزال المعيار للنص الشكلي منذ القرن الخامس عشر عندما قامت مطبعة مجهولة برص مجموعة من الأحرف بشكل عشوائي أخذتها من نص، لتكوّن كتيّب بمثابة دليل أو مرجع شكلي لهذه الأحرف. خمسة قرون من الزمن لم تقضي على هذا النص، بل انه حتى صار مستخدماً وبشكله الأصلي في الطباعة والتنضيد الإلكتروني. انتشر بشكل كبير في ستينيّات هذا القرن مع إصدار رقائق "ليتراسيت" (Letraset) البلاستيكية تحوي مقاطع من هذا النص، وعاد لينتشر مرة أخرى مؤخراَ مع ظهور برامج النشر الإلكتروني مثل "ألدوس بايج مايكر" (Aldus PageMaker) والتي حوت أيضاً على نسخ من نص لوريم إيبسوم.',
                    'input_type' => 2,
                    'category' => 1,
                    'created_at' => '2020-06-14 18:29:45',
                    'updated_at' => '2020-06-14 18:29:45',
                ),
            13 =>
                array (
                    'id' => 89,
                    'name' => 'about_en',
                    'slug_ar' => 'من نحن باللغة الانجليزية',
                    'slug_en' => 'About Us In English',
                    'value' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum',
                    'input_type' => 2,
                    'category' => 1,
                    'created_at' => '2020-06-14 18:29:45',
                    'updated_at' => '2020-06-14 18:29:45',
                ),
            14 =>
                array (
                    'id' => 90,
                    'name' => 'policy_ar',
                    'slug_ar' => 'الشروط والاحكام باللغة العربية',
                    'slug_en' => 'Terms And Conditions In Arabic',
                    'value' => 'وريم إيبسوم(Lorem Ipsum) هو ببساطة نص شكلي (بمعنى أن الغاية هي الشكل وليس المحتوى) ويُستخدم في صناعات المطابع ودور النشر. كان لوريم إيبسوم ولايزال المعيار للنص الشكلي منذ القرن الخامس عشر عندما قامت مطبعة مجهولة برص مجموعة من الأحرف بشكل عشوائي أخذتها من نص، لتكوّن كتيّب بمثابة دليل أو مرجع شكلي لهذه الأحرف. خمسة قرون من الزمن لم تقضي على هذا النص، بل انه حتى صار مستخدماً وبشكله الأصلي في الطباعة والتنضيد الإلكتروني. انتشر بشكل كبير في ستينيّات هذا القرن مع إصدار رقائق "ليتراسيت" (Letraset) البلاستيكية تحوي مقاطع من هذا النص، وعاد لينتشر مرة أخرى مؤخراَ مع ظهور برامج النشر الإلكتروني مثل "ألدوس بايج مايكر" (Aldus PageMaker) والتي حوت أيضاً على نسخ من نص لوريم إيبسوم.',
                    'input_type' => 2,
                    'category' => 1,
                    'created_at' => '2020-06-14 18:29:45',
                    'updated_at' => '2020-06-14 18:29:45',
                ),
            15 =>
                array (
                    'id' => 91,
                    'name' => 'policy_en',
                    'slug_ar' => 'الشروط والاحكام باللغة الانجليزية',
                    'slug_en' => 'Terms And Conditions In English',
                    'value' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum',
                    'input_type' => 2,
                    'category' => 1,
                    'created_at' => '2020-06-14 18:29:45',
                    'updated_at' => '2020-06-14 18:29:45',
                ),
            16 =>
                array (
                    'id' => 117,
                    'name' => 'about_ar',
                    'slug_ar' => 'من نحن باللغة العربية',
                    'slug_en' => 'About Us In Arabic',
                    'value' => 'وريم إيبسوم(Lorem Ipsum) هو ببساطة نص شكلي (بمعنى أن الغاية هي الشكل وليس المحتوى) ويُستخدم في صناعات المطابع ودور النشر. كان لوريم إيبسوم ولايزال المعيار للنص الشكلي منذ القرن الخامس عشر عندما قامت مطبعة مجهولة برص مجموعة من الأحرف بشكل عشوائي أخذتها من نص، لتكوّن كتيّب بمثابة دليل أو مرجع شكلي لهذه الأحرف. خمسة قرون من الزمن لم تقضي على هذا النص، بل انه حتى صار مستخدماً وبشكله الأصلي في الطباعة والتنضيد الإلكتروني. انتشر بشكل كبير في ستينيّات هذا القرن مع إصدار رقائق "ليتراسيت" (Letraset) البلاستيكية تحوي مقاطع من هذا النص، وعاد لينتشر مرة أخرى مؤخراَ مع ظهور برامج النشر الإلكتروني مثل "ألدوس بايج مايكر" (Aldus PageMaker) والتي حوت أيضاً على نسخ من نص لوريم إيبسوم.',
                    'input_type' => 2,
                    'category' => 1,
                    'created_at' => '2020-06-14 18:29:59',
                    'updated_at' => '2020-06-14 18:29:59',
                ),
            17 =>
                array (
                    'id' => 118,
                    'name' => 'about_en',
                    'slug_ar' => 'من نحن باللغة الانجليزية',
                    'slug_en' => 'About Us In English',
                    'value' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum',
                    'input_type' => 2,
                    'category' => 1,
                    'created_at' => '2020-06-14 18:29:59',
                    'updated_at' => '2020-06-14 18:29:59',
                ),
            18 =>
                array (
                    'id' => 119,
                    'name' => 'policy_ar',
                    'slug_ar' => 'الشروط والاحكام باللغة العربية',
                    'slug_en' => 'Terms And Conditions In Arabic',
                    'value' => 'وريم إيبسوم(Lorem Ipsum) هو ببساطة نص شكلي (بمعنى أن الغاية هي الشكل وليس المحتوى) ويُستخدم في صناعات المطابع ودور النشر. كان لوريم إيبسوم ولايزال المعيار للنص الشكلي منذ القرن الخامس عشر عندما قامت مطبعة مجهولة برص مجموعة من الأحرف بشكل عشوائي أخذتها من نص، لتكوّن كتيّب بمثابة دليل أو مرجع شكلي لهذه الأحرف. خمسة قرون من الزمن لم تقضي على هذا النص، بل انه حتى صار مستخدماً وبشكله الأصلي في الطباعة والتنضيد الإلكتروني. انتشر بشكل كبير في ستينيّات هذا القرن مع إصدار رقائق "ليتراسيت" (Letraset) البلاستيكية تحوي مقاطع من هذا النص، وعاد لينتشر مرة أخرى مؤخراَ مع ظهور برامج النشر الإلكتروني مثل "ألدوس بايج مايكر" (Aldus PageMaker) والتي حوت أيضاً على نسخ من نص لوريم إيبسوم.',
                    'input_type' => 2,
                    'category' => 1,
                    'created_at' => '2020-06-14 18:29:59',
                    'updated_at' => '2020-06-14 18:29:59',
                ),
            19 =>
                array (
                    'id' => 120,
                    'name' => 'policy_en',
                    'slug_ar' => 'الشروط والاحكام باللغة الانجليزية',
                    'slug_en' => 'Terms And Conditions In English',
                    'value' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum',
                    'input_type' => 2,
                    'category' => 1,
                    'created_at' => '2020-06-14 18:29:59',
                    'updated_at' => '2020-06-14 18:29:59',
                ),
            20 =>
                array (
                    'id' => 146,
                    'name' => 'about_ar',
                    'slug_ar' => 'من نحن باللغة العربية',
                    'slug_en' => 'About Us In Arabic',
                    'value' => 'وريم إيبسوم(Lorem Ipsum) هو ببساطة نص شكلي (بمعنى أن الغاية هي الشكل وليس المحتوى) ويُستخدم في صناعات المطابع ودور النشر. كان لوريم إيبسوم ولايزال المعيار للنص الشكلي منذ القرن الخامس عشر عندما قامت مطبعة مجهولة برص مجموعة من الأحرف بشكل عشوائي أخذتها من نص، لتكوّن كتيّب بمثابة دليل أو مرجع شكلي لهذه الأحرف. خمسة قرون من الزمن لم تقضي على هذا النص، بل انه حتى صار مستخدماً وبشكله الأصلي في الطباعة والتنضيد الإلكتروني. انتشر بشكل كبير في ستينيّات هذا القرن مع إصدار رقائق "ليتراسيت" (Letraset) البلاستيكية تحوي مقاطع من هذا النص، وعاد لينتشر مرة أخرى مؤخراَ مع ظهور برامج النشر الإلكتروني مثل "ألدوس بايج مايكر" (Aldus PageMaker) والتي حوت أيضاً على نسخ من نص لوريم إيبسوم.',
                    'input_type' => 2,
                    'category' => 1,
                    'created_at' => '2020-06-14 18:30:43',
                    'updated_at' => '2020-06-14 18:30:43',
                ),
            21 =>
                array (
                    'id' => 147,
                    'name' => 'about_en',
                    'slug_ar' => 'من نحن باللغة الانجليزية',
                    'slug_en' => 'About Us In English',
                    'value' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum',
                    'input_type' => 2,
                    'category' => 1,
                    'created_at' => '2020-06-14 18:30:43',
                    'updated_at' => '2020-06-14 18:30:43',
                ),
            22 =>
                array (
                    'id' => 148,
                    'name' => 'policy_ar',
                    'slug_ar' => 'الشروط والاحكام باللغة العربية',
                    'slug_en' => 'Terms And Conditions In Arabic',
                    'value' => 'وريم إيبسوم(Lorem Ipsum) هو ببساطة نص شكلي (بمعنى أن الغاية هي الشكل وليس المحتوى) ويُستخدم في صناعات المطابع ودور النشر. كان لوريم إيبسوم ولايزال المعيار للنص الشكلي منذ القرن الخامس عشر عندما قامت مطبعة مجهولة برص مجموعة من الأحرف بشكل عشوائي أخذتها من نص، لتكوّن كتيّب بمثابة دليل أو مرجع شكلي لهذه الأحرف. خمسة قرون من الزمن لم تقضي على هذا النص، بل انه حتى صار مستخدماً وبشكله الأصلي في الطباعة والتنضيد الإلكتروني. انتشر بشكل كبير في ستينيّات هذا القرن مع إصدار رقائق "ليتراسيت" (Letraset) البلاستيكية تحوي مقاطع من هذا النص، وعاد لينتشر مرة أخرى مؤخراَ مع ظهور برامج النشر الإلكتروني مثل "ألدوس بايج مايكر" (Aldus PageMaker) والتي حوت أيضاً على نسخ من نص لوريم إيبسوم.',
                    'input_type' => 2,
                    'category' => 1,
                    'created_at' => '2020-06-14 18:30:43',
                    'updated_at' => '2020-06-14 18:30:43',
                ),
            23 =>
                array (
                    'id' => 149,
                    'name' => 'policy_en',
                    'slug_ar' => 'الشروط والاحكام باللغة الانجليزية',
                    'slug_en' => 'Terms And Conditions In English',
                    'value' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum',
                    'input_type' => 2,
                    'category' => 1,
                    'created_at' => '2020-06-14 18:30:43',
                    'updated_at' => '2020-06-14 18:30:43',
                ),
            24 =>
                array (
                    'id' => 175,
                    'name' => 'about_ar',
                    'slug_ar' => 'من نحن باللغة العربية',
                    'slug_en' => 'About Us In Arabic',
                    'value' => 'وريم إيبسوم(Lorem Ipsum) هو ببساطة نص شكلي (بمعنى أن الغاية هي الشكل وليس المحتوى) ويُستخدم في صناعات المطابع ودور النشر. كان لوريم إيبسوم ولايزال المعيار للنص الشكلي منذ القرن الخامس عشر عندما قامت مطبعة مجهولة برص مجموعة من الأحرف بشكل عشوائي أخذتها من نص، لتكوّن كتيّب بمثابة دليل أو مرجع شكلي لهذه الأحرف. خمسة قرون من الزمن لم تقضي على هذا النص، بل انه حتى صار مستخدماً وبشكله الأصلي في الطباعة والتنضيد الإلكتروني. انتشر بشكل كبير في ستينيّات هذا القرن مع إصدار رقائق "ليتراسيت" (Letraset) البلاستيكية تحوي مقاطع من هذا النص، وعاد لينتشر مرة أخرى مؤخراَ مع ظهور برامج النشر الإلكتروني مثل "ألدوس بايج مايكر" (Aldus PageMaker) والتي حوت أيضاً على نسخ من نص لوريم إيبسوم.',
                    'input_type' => 2,
                    'category' => 1,
                    'created_at' => '2020-06-14 18:34:32',
                    'updated_at' => '2020-06-14 18:34:32',
                ),
            25 =>
                array (
                    'id' => 176,
                    'name' => 'about_en',
                    'slug_ar' => 'من نحن باللغة الانجليزية',
                    'slug_en' => 'About Us In English',
                    'value' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum',
                    'input_type' => 2,
                    'category' => 1,
                    'created_at' => '2020-06-14 18:34:32',
                    'updated_at' => '2020-06-14 18:34:32',
                ),
            26 =>
                array (
                    'id' => 177,
                    'name' => 'policy_ar',
                    'slug_ar' => 'الشروط والاحكام باللغة العربية',
                    'slug_en' => 'Terms And Conditions In Arabic',
                    'value' => 'وريم إيبسوم(Lorem Ipsum) هو ببساطة نص شكلي (بمعنى أن الغاية هي الشكل وليس المحتوى) ويُستخدم في صناعات المطابع ودور النشر. كان لوريم إيبسوم ولايزال المعيار للنص الشكلي منذ القرن الخامس عشر عندما قامت مطبعة مجهولة برص مجموعة من الأحرف بشكل عشوائي أخذتها من نص، لتكوّن كتيّب بمثابة دليل أو مرجع شكلي لهذه الأحرف. خمسة قرون من الزمن لم تقضي على هذا النص، بل انه حتى صار مستخدماً وبشكله الأصلي في الطباعة والتنضيد الإلكتروني. انتشر بشكل كبير في ستينيّات هذا القرن مع إصدار رقائق "ليتراسيت" (Letraset) البلاستيكية تحوي مقاطع من هذا النص، وعاد لينتشر مرة أخرى مؤخراَ مع ظهور برامج النشر الإلكتروني مثل "ألدوس بايج مايكر" (Aldus PageMaker) والتي حوت أيضاً على نسخ من نص لوريم إيبسوم.',
                    'input_type' => 2,
                    'category' => 1,
                    'created_at' => '2020-06-14 18:34:32',
                    'updated_at' => '2020-06-14 18:34:32',
                ),
            27 =>
                array (
                    'id' => 178,
                    'name' => 'policy_en',
                    'slug_ar' => 'الشروط والاحكام باللغة الانجليزية',
                    'slug_en' => 'Terms And Conditions In English',
                    'value' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum',
                    'input_type' => 2,
                    'category' => 1,
                    'created_at' => '2020-06-14 18:34:32',
                    'updated_at' => '2020-06-14 18:34:32',
                ),
            28 =>
                array (
                    'id' => 204,
                    'name' => 'about_ar',
                    'slug_ar' => 'من نحن باللغة العربية',
                    'slug_en' => 'About Us In Arabic',
                    'value' => 'وريم إيبسوم(Lorem Ipsum) هو ببساطة نص شكلي (بمعنى أن الغاية هي الشكل وليس المحتوى) ويُستخدم في صناعات المطابع ودور النشر. كان لوريم إيبسوم ولايزال المعيار للنص الشكلي منذ القرن الخامس عشر عندما قامت مطبعة مجهولة برص مجموعة من الأحرف بشكل عشوائي أخذتها من نص، لتكوّن كتيّب بمثابة دليل أو مرجع شكلي لهذه الأحرف. خمسة قرون من الزمن لم تقضي على هذا النص، بل انه حتى صار مستخدماً وبشكله الأصلي في الطباعة والتنضيد الإلكتروني. انتشر بشكل كبير في ستينيّات هذا القرن مع إصدار رقائق "ليتراسيت" (Letraset) البلاستيكية تحوي مقاطع من هذا النص، وعاد لينتشر مرة أخرى مؤخراَ مع ظهور برامج النشر الإلكتروني مثل "ألدوس بايج مايكر" (Aldus PageMaker) والتي حوت أيضاً على نسخ من نص لوريم إيبسوم.',
                    'input_type' => 2,
                    'category' => 1,
                    'created_at' => '2020-06-14 18:34:54',
                    'updated_at' => '2020-06-14 18:34:54',
                ),
            29 =>
                array (
                    'id' => 205,
                    'name' => 'about_en',
                    'slug_ar' => 'من نحن باللغة الانجليزية',
                    'slug_en' => 'About Us In English',
                    'value' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum',
                    'input_type' => 2,
                    'category' => 1,
                    'created_at' => '2020-06-14 18:34:54',
                    'updated_at' => '2020-06-14 18:34:54',
                ),
            30 =>
                array (
                    'id' => 206,
                    'name' => 'policy_ar',
                    'slug_ar' => 'الشروط والاحكام باللغة العربية',
                    'slug_en' => 'Terms And Conditions In Arabic',
                    'value' => 'وريم إيبسوم(Lorem Ipsum) هو ببساطة نص شكلي (بمعنى أن الغاية هي الشكل وليس المحتوى) ويُستخدم في صناعات المطابع ودور النشر. كان لوريم إيبسوم ولايزال المعيار للنص الشكلي منذ القرن الخامس عشر عندما قامت مطبعة مجهولة برص مجموعة من الأحرف بشكل عشوائي أخذتها من نص، لتكوّن كتيّب بمثابة دليل أو مرجع شكلي لهذه الأحرف. خمسة قرون من الزمن لم تقضي على هذا النص، بل انه حتى صار مستخدماً وبشكله الأصلي في الطباعة والتنضيد الإلكتروني. انتشر بشكل كبير في ستينيّات هذا القرن مع إصدار رقائق "ليتراسيت" (Letraset) البلاستيكية تحوي مقاطع من هذا النص، وعاد لينتشر مرة أخرى مؤخراَ مع ظهور برامج النشر الإلكتروني مثل "ألدوس بايج مايكر" (Aldus PageMaker) والتي حوت أيضاً على نسخ من نص لوريم إيبسوم.',
                    'input_type' => 2,
                    'category' => 1,
                    'created_at' => '2020-06-14 18:34:54',
                    'updated_at' => '2020-06-14 18:34:54',
                ),
            31 =>
                array (
                    'id' => 207,
                    'name' => 'policy_en',
                    'slug_ar' => 'الشروط والاحكام باللغة الانجليزية',
                    'slug_en' => 'Terms And Conditions In English',
                    'value' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum',
                    'input_type' => 2,
                    'category' => 1,
                    'created_at' => '2020-06-14 18:34:55',
                    'updated_at' => '2020-06-14 18:34:55',
                ),
            32 =>
                array (
                    'id' => 233,
                    'name' => 'about_ar',
                    'slug_ar' => 'من نحن باللغة العربية',
                    'slug_en' => 'About Us In Arabic',
                    'value' => 'وريم إيبسوم(Lorem Ipsum) هو ببساطة نص شكلي (بمعنى أن الغاية هي الشكل وليس المحتوى) ويُستخدم في صناعات المطابع ودور النشر. كان لوريم إيبسوم ولايزال المعيار للنص الشكلي منذ القرن الخامس عشر عندما قامت مطبعة مجهولة برص مجموعة من الأحرف بشكل عشوائي أخذتها من نص، لتكوّن كتيّب بمثابة دليل أو مرجع شكلي لهذه الأحرف. خمسة قرون من الزمن لم تقضي على هذا النص، بل انه حتى صار مستخدماً وبشكله الأصلي في الطباعة والتنضيد الإلكتروني. انتشر بشكل كبير في ستينيّات هذا القرن مع إصدار رقائق "ليتراسيت" (Letraset) البلاستيكية تحوي مقاطع من هذا النص، وعاد لينتشر مرة أخرى مؤخراَ مع ظهور برامج النشر الإلكتروني مثل "ألدوس بايج مايكر" (Aldus PageMaker) والتي حوت أيضاً على نسخ من نص لوريم إيبسوم.',
                    'input_type' => 2,
                    'category' => 1,
                    'created_at' => '2020-06-14 18:36:23',
                    'updated_at' => '2020-06-14 18:36:23',
                ),
            33 =>
                array (
                    'id' => 234,
                    'name' => 'about_en',
                    'slug_ar' => 'من نحن باللغة الانجليزية',
                    'slug_en' => 'About Us In English',
                    'value' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum',
                    'input_type' => 2,
                    'category' => 1,
                    'created_at' => '2020-06-14 18:36:23',
                    'updated_at' => '2020-06-14 18:36:23',
                ),
            34 =>
                array (
                    'id' => 235,
                    'name' => 'policy_ar',
                    'slug_ar' => 'الشروط والاحكام باللغة العربية',
                    'slug_en' => 'Terms And Conditions In Arabic',
                    'value' => 'وريم إيبسوم(Lorem Ipsum) هو ببساطة نص شكلي (بمعنى أن الغاية هي الشكل وليس المحتوى) ويُستخدم في صناعات المطابع ودور النشر. كان لوريم إيبسوم ولايزال المعيار للنص الشكلي منذ القرن الخامس عشر عندما قامت مطبعة مجهولة برص مجموعة من الأحرف بشكل عشوائي أخذتها من نص، لتكوّن كتيّب بمثابة دليل أو مرجع شكلي لهذه الأحرف. خمسة قرون من الزمن لم تقضي على هذا النص، بل انه حتى صار مستخدماً وبشكله الأصلي في الطباعة والتنضيد الإلكتروني. انتشر بشكل كبير في ستينيّات هذا القرن مع إصدار رقائق "ليتراسيت" (Letraset) البلاستيكية تحوي مقاطع من هذا النص، وعاد لينتشر مرة أخرى مؤخراَ مع ظهور برامج النشر الإلكتروني مثل "ألدوس بايج مايكر" (Aldus PageMaker) والتي حوت أيضاً على نسخ من نص لوريم إيبسوم.',
                    'input_type' => 2,
                    'category' => 1,
                    'created_at' => '2020-06-14 18:36:23',
                    'updated_at' => '2020-06-14 18:36:23',
                ),
            35 =>
                array (
                    'id' => 236,
                    'name' => 'policy_en',
                    'slug_ar' => 'الشروط والاحكام باللغة الانجليزية',
                    'slug_en' => 'Terms And Conditions In English',
                    'value' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum',
                    'input_type' => 2,
                    'category' => 1,
                    'created_at' => '2020-06-14 18:36:23',
                    'updated_at' => '2020-06-14 18:36:23',
                ),
            36 =>
                array (
                    'id' => 262,
                    'name' => 'about_ar',
                    'slug_ar' => 'من نحن باللغة العربية',
                    'slug_en' => 'About Us In Arabic',
                    'value' => 'وريم إيبسوم(Lorem Ipsum) هو ببساطة نص شكلي (بمعنى أن الغاية هي الشكل وليس المحتوى) ويُستخدم في صناعات المطابع ودور النشر. كان لوريم إيبسوم ولايزال المعيار للنص الشكلي منذ القرن الخامس عشر عندما قامت مطبعة مجهولة برص مجموعة من الأحرف بشكل عشوائي أخذتها من نص، لتكوّن كتيّب بمثابة دليل أو مرجع شكلي لهذه الأحرف. خمسة قرون من الزمن لم تقضي على هذا النص، بل انه حتى صار مستخدماً وبشكله الأصلي في الطباعة والتنضيد الإلكتروني. انتشر بشكل كبير في ستينيّات هذا القرن مع إصدار رقائق "ليتراسيت" (Letraset) البلاستيكية تحوي مقاطع من هذا النص، وعاد لينتشر مرة أخرى مؤخراَ مع ظهور برامج النشر الإلكتروني مثل "ألدوس بايج مايكر" (Aldus PageMaker) والتي حوت أيضاً على نسخ من نص لوريم إيبسوم.',
                    'input_type' => 2,
                    'category' => 1,
                    'created_at' => '2020-06-14 18:38:30',
                    'updated_at' => '2020-06-14 18:38:30',
                ),
            37 =>
                array (
                    'id' => 263,
                    'name' => 'about_en',
                    'slug_ar' => 'من نحن باللغة الانجليزية',
                    'slug_en' => 'About Us In English',
                    'value' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum',
                    'input_type' => 2,
                    'category' => 1,
                    'created_at' => '2020-06-14 18:38:30',
                    'updated_at' => '2020-06-14 18:38:30',
                ),
            38 =>
                array (
                    'id' => 264,
                    'name' => 'policy_ar',
                    'slug_ar' => 'الشروط والاحكام باللغة العربية',
                    'slug_en' => 'Terms And Conditions In Arabic',
                    'value' => 'وريم إيبسوم(Lorem Ipsum) هو ببساطة نص شكلي (بمعنى أن الغاية هي الشكل وليس المحتوى) ويُستخدم في صناعات المطابع ودور النشر. كان لوريم إيبسوم ولايزال المعيار للنص الشكلي منذ القرن الخامس عشر عندما قامت مطبعة مجهولة برص مجموعة من الأحرف بشكل عشوائي أخذتها من نص، لتكوّن كتيّب بمثابة دليل أو مرجع شكلي لهذه الأحرف. خمسة قرون من الزمن لم تقضي على هذا النص، بل انه حتى صار مستخدماً وبشكله الأصلي في الطباعة والتنضيد الإلكتروني. انتشر بشكل كبير في ستينيّات هذا القرن مع إصدار رقائق "ليتراسيت" (Letraset) البلاستيكية تحوي مقاطع من هذا النص، وعاد لينتشر مرة أخرى مؤخراَ مع ظهور برامج النشر الإلكتروني مثل "ألدوس بايج مايكر" (Aldus PageMaker) والتي حوت أيضاً على نسخ من نص لوريم إيبسوم.',
                    'input_type' => 2,
                    'category' => 1,
                    'created_at' => '2020-06-14 18:38:30',
                    'updated_at' => '2020-06-14 18:38:30',
                ),
            39 =>
                array (
                    'id' => 265,
                    'name' => 'policy_en',
                    'slug_ar' => 'الشروط والاحكام باللغة الانجليزية',
                    'slug_en' => 'Terms And Conditions In English',
                    'value' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum',
                    'input_type' => 2,
                    'category' => 1,
                    'created_at' => '2020-06-14 18:38:30',
                    'updated_at' => '2020-06-14 18:38:30',
                ),
            40 =>
                array (
                    'id' => 291,
                    'name' => 'about_ar',
                    'slug_ar' => 'من نحن باللغة العربية',
                    'slug_en' => 'About Us In Arabic',
                    'value' => 'وريم إيبسوم(Lorem Ipsum) هو ببساطة نص شكلي (بمعنى أن الغاية هي الشكل وليس المحتوى) ويُستخدم في صناعات المطابع ودور النشر. كان لوريم إيبسوم ولايزال المعيار للنص الشكلي منذ القرن الخامس عشر عندما قامت مطبعة مجهولة برص مجموعة من الأحرف بشكل عشوائي أخذتها من نص، لتكوّن كتيّب بمثابة دليل أو مرجع شكلي لهذه الأحرف. خمسة قرون من الزمن لم تقضي على هذا النص، بل انه حتى صار مستخدماً وبشكله الأصلي في الطباعة والتنضيد الإلكتروني. انتشر بشكل كبير في ستينيّات هذا القرن مع إصدار رقائق "ليتراسيت" (Letraset) البلاستيكية تحوي مقاطع من هذا النص، وعاد لينتشر مرة أخرى مؤخراَ مع ظهور برامج النشر الإلكتروني مثل "ألدوس بايج مايكر" (Aldus PageMaker) والتي حوت أيضاً على نسخ من نص لوريم إيبسوم.',
                    'input_type' => 2,
                    'category' => 1,
                    'created_at' => '2020-06-14 18:38:47',
                    'updated_at' => '2020-06-14 18:38:47',
                ),
            41 =>
                array (
                    'id' => 292,
                    'name' => 'about_en',
                    'slug_ar' => 'من نحن باللغة الانجليزية',
                    'slug_en' => 'About Us In English',
                    'value' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum',
                    'input_type' => 2,
                    'category' => 1,
                    'created_at' => '2020-06-14 18:38:47',
                    'updated_at' => '2020-06-14 18:38:47',
                ),
            42 =>
                array (
                    'id' => 293,
                    'name' => 'policy_ar',
                    'slug_ar' => 'الشروط والاحكام باللغة العربية',
                    'slug_en' => 'Terms And Conditions In Arabic',
                    'value' => 'وريم إيبسوم(Lorem Ipsum) هو ببساطة نص شكلي (بمعنى أن الغاية هي الشكل وليس المحتوى) ويُستخدم في صناعات المطابع ودور النشر. كان لوريم إيبسوم ولايزال المعيار للنص الشكلي منذ القرن الخامس عشر عندما قامت مطبعة مجهولة برص مجموعة من الأحرف بشكل عشوائي أخذتها من نص، لتكوّن كتيّب بمثابة دليل أو مرجع شكلي لهذه الأحرف. خمسة قرون من الزمن لم تقضي على هذا النص، بل انه حتى صار مستخدماً وبشكله الأصلي في الطباعة والتنضيد الإلكتروني. انتشر بشكل كبير في ستينيّات هذا القرن مع إصدار رقائق "ليتراسيت" (Letraset) البلاستيكية تحوي مقاطع من هذا النص، وعاد لينتشر مرة أخرى مؤخراَ مع ظهور برامج النشر الإلكتروني مثل "ألدوس بايج مايكر" (Aldus PageMaker) والتي حوت أيضاً على نسخ من نص لوريم إيبسوم.',
                    'input_type' => 2,
                    'category' => 1,
                    'created_at' => '2020-06-14 18:38:47',
                    'updated_at' => '2020-06-14 18:38:47',
                ),
            43 =>
                array (
                    'id' => 294,
                    'name' => 'policy_en',
                    'slug_ar' => 'الشروط والاحكام باللغة الانجليزية',
                    'slug_en' => 'Terms And Conditions In English',
                    'value' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum',
                    'input_type' => 2,
                    'category' => 1,
                    'created_at' => '2020-06-14 18:38:47',
                    'updated_at' => '2020-06-14 18:38:47',
                ),
            44 =>
                array (
                    'id' => 320,
                    'name' => 'about_ar',
                    'slug_ar' => 'من نحن باللغة العربية',
                    'slug_en' => 'About Us In Arabic',
                    'value' => 'وريم إيبسوم(Lorem Ipsum) هو ببساطة نص شكلي (بمعنى أن الغاية هي الشكل وليس المحتوى) ويُستخدم في صناعات المطابع ودور النشر. كان لوريم إيبسوم ولايزال المعيار للنص الشكلي منذ القرن الخامس عشر عندما قامت مطبعة مجهولة برص مجموعة من الأحرف بشكل عشوائي أخذتها من نص، لتكوّن كتيّب بمثابة دليل أو مرجع شكلي لهذه الأحرف. خمسة قرون من الزمن لم تقضي على هذا النص، بل انه حتى صار مستخدماً وبشكله الأصلي في الطباعة والتنضيد الإلكتروني. انتشر بشكل كبير في ستينيّات هذا القرن مع إصدار رقائق "ليتراسيت" (Letraset) البلاستيكية تحوي مقاطع من هذا النص، وعاد لينتشر مرة أخرى مؤخراَ مع ظهور برامج النشر الإلكتروني مثل "ألدوس بايج مايكر" (Aldus PageMaker) والتي حوت أيضاً على نسخ من نص لوريم إيبسوم.',
                    'input_type' => 2,
                    'category' => 1,
                    'created_at' => '2020-06-14 18:39:18',
                    'updated_at' => '2020-06-14 18:39:18',
                ),
            45 =>
                array (
                    'id' => 321,
                    'name' => 'about_en',
                    'slug_ar' => 'من نحن باللغة الانجليزية',
                    'slug_en' => 'About Us In English',
                    'value' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum',
                    'input_type' => 2,
                    'category' => 1,
                    'created_at' => '2020-06-14 18:39:18',
                    'updated_at' => '2020-06-14 18:39:18',
                ),
            46 =>
                array (
                    'id' => 322,
                    'name' => 'policy_ar',
                    'slug_ar' => 'الشروط والاحكام باللغة العربية',
                    'slug_en' => 'Terms And Conditions In Arabic',
                    'value' => 'وريم إيبسوم(Lorem Ipsum) هو ببساطة نص شكلي (بمعنى أن الغاية هي الشكل وليس المحتوى) ويُستخدم في صناعات المطابع ودور النشر. كان لوريم إيبسوم ولايزال المعيار للنص الشكلي منذ القرن الخامس عشر عندما قامت مطبعة مجهولة برص مجموعة من الأحرف بشكل عشوائي أخذتها من نص، لتكوّن كتيّب بمثابة دليل أو مرجع شكلي لهذه الأحرف. خمسة قرون من الزمن لم تقضي على هذا النص، بل انه حتى صار مستخدماً وبشكله الأصلي في الطباعة والتنضيد الإلكتروني. انتشر بشكل كبير في ستينيّات هذا القرن مع إصدار رقائق "ليتراسيت" (Letraset) البلاستيكية تحوي مقاطع من هذا النص، وعاد لينتشر مرة أخرى مؤخراَ مع ظهور برامج النشر الإلكتروني مثل "ألدوس بايج مايكر" (Aldus PageMaker) والتي حوت أيضاً على نسخ من نص لوريم إيبسوم.',
                    'input_type' => 2,
                    'category' => 1,
                    'created_at' => '2020-06-14 18:39:18',
                    'updated_at' => '2020-06-14 18:39:18',
                ),
            47 =>
                array (
                    'id' => 323,
                    'name' => 'policy_en',
                    'slug_ar' => 'الشروط والاحكام باللغة الانجليزية',
                    'slug_en' => 'Terms And Conditions In English',
                    'value' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum',
                    'input_type' => 2,
                    'category' => 1,
                    'created_at' => '2020-06-14 18:39:18',
                    'updated_at' => '2020-06-14 18:39:18',
                ),
            48 =>
                array (
                    'id' => 349,
                    'name' => 'about_ar',
                    'slug_ar' => 'من نحن باللغة العربية',
                    'slug_en' => 'About Us In Arabic',
                    'value' => 'وريم إيبسوم(Lorem Ipsum) هو ببساطة نص شكلي (بمعنى أن الغاية هي الشكل وليس المحتوى) ويُستخدم في صناعات المطابع ودور النشر. كان لوريم إيبسوم ولايزال المعيار للنص الشكلي منذ القرن الخامس عشر عندما قامت مطبعة مجهولة برص مجموعة من الأحرف بشكل عشوائي أخذتها من نص، لتكوّن كتيّب بمثابة دليل أو مرجع شكلي لهذه الأحرف. خمسة قرون من الزمن لم تقضي على هذا النص، بل انه حتى صار مستخدماً وبشكله الأصلي في الطباعة والتنضيد الإلكتروني. انتشر بشكل كبير في ستينيّات هذا القرن مع إصدار رقائق "ليتراسيت" (Letraset) البلاستيكية تحوي مقاطع من هذا النص، وعاد لينتشر مرة أخرى مؤخراَ مع ظهور برامج النشر الإلكتروني مثل "ألدوس بايج مايكر" (Aldus PageMaker) والتي حوت أيضاً على نسخ من نص لوريم إيبسوم.',
                    'input_type' => 2,
                    'category' => 1,
                    'created_at' => '2020-06-14 18:39:56',
                    'updated_at' => '2020-06-14 18:39:56',
                ),
            49 =>
                array (
                    'id' => 350,
                    'name' => 'about_en',
                    'slug_ar' => 'من نحن باللغة الانجليزية',
                    'slug_en' => 'About Us In English',
                    'value' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum',
                    'input_type' => 2,
                    'category' => 1,
                    'created_at' => '2020-06-14 18:39:56',
                    'updated_at' => '2020-06-14 18:39:56',
                ),
            50 =>
                array (
                    'id' => 351,
                    'name' => 'policy_ar',
                    'slug_ar' => 'الشروط والاحكام باللغة العربية',
                    'slug_en' => 'Terms And Conditions In Arabic',
                    'value' => 'وريم إيبسوم(Lorem Ipsum) هو ببساطة نص شكلي (بمعنى أن الغاية هي الشكل وليس المحتوى) ويُستخدم في صناعات المطابع ودور النشر. كان لوريم إيبسوم ولايزال المعيار للنص الشكلي منذ القرن الخامس عشر عندما قامت مطبعة مجهولة برص مجموعة من الأحرف بشكل عشوائي أخذتها من نص، لتكوّن كتيّب بمثابة دليل أو مرجع شكلي لهذه الأحرف. خمسة قرون من الزمن لم تقضي على هذا النص، بل انه حتى صار مستخدماً وبشكله الأصلي في الطباعة والتنضيد الإلكتروني. انتشر بشكل كبير في ستينيّات هذا القرن مع إصدار رقائق "ليتراسيت" (Letraset) البلاستيكية تحوي مقاطع من هذا النص، وعاد لينتشر مرة أخرى مؤخراَ مع ظهور برامج النشر الإلكتروني مثل "ألدوس بايج مايكر" (Aldus PageMaker) والتي حوت أيضاً على نسخ من نص لوريم إيبسوم.',
                    'input_type' => 2,
                    'category' => 1,
                    'created_at' => '2020-06-14 18:39:56',
                    'updated_at' => '2020-06-14 18:39:56',
                ),
            51 =>
                array (
                    'id' => 352,
                    'name' => 'policy_en',
                    'slug_ar' => 'الشروط والاحكام باللغة الانجليزية',
                    'slug_en' => 'Terms And Conditions In English',
                    'value' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum',
                    'input_type' => 2,
                    'category' => 1,
                    'created_at' => '2020-06-14 18:39:56',
                    'updated_at' => '2020-06-14 18:39:56',
                ),
            52 =>
                array (
                    'id' => 378,
                    'name' => 'about_ar',
                    'slug_ar' => 'من نحن باللغة العربية',
                    'slug_en' => 'About Us In Arabic',
                    'value' => 'وريم إيبسوم(Lorem Ipsum) هو ببساطة نص شكلي (بمعنى أن الغاية هي الشكل وليس المحتوى) ويُستخدم في صناعات المطابع ودور النشر. كان لوريم إيبسوم ولايزال المعيار للنص الشكلي منذ القرن الخامس عشر عندما قامت مطبعة مجهولة برص مجموعة من الأحرف بشكل عشوائي أخذتها من نص، لتكوّن كتيّب بمثابة دليل أو مرجع شكلي لهذه الأحرف. خمسة قرون من الزمن لم تقضي على هذا النص، بل انه حتى صار مستخدماً وبشكله الأصلي في الطباعة والتنضيد الإلكتروني. انتشر بشكل كبير في ستينيّات هذا القرن مع إصدار رقائق "ليتراسيت" (Letraset) البلاستيكية تحوي مقاطع من هذا النص، وعاد لينتشر مرة أخرى مؤخراَ مع ظهور برامج النشر الإلكتروني مثل "ألدوس بايج مايكر" (Aldus PageMaker) والتي حوت أيضاً على نسخ من نص لوريم إيبسوم.',
                    'input_type' => 2,
                    'category' => 1,
                    'created_at' => '2020-06-14 18:40:09',
                    'updated_at' => '2020-06-14 18:40:09',
                ),
            53 =>
                array (
                    'id' => 379,
                    'name' => 'about_en',
                    'slug_ar' => 'من نحن باللغة الانجليزية',
                    'slug_en' => 'About Us In English',
                    'value' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum',
                    'input_type' => 2,
                    'category' => 1,
                    'created_at' => '2020-06-14 18:40:09',
                    'updated_at' => '2020-06-14 18:40:09',
                ),
            54 =>
                array (
                    'id' => 380,
                    'name' => 'policy_ar',
                    'slug_ar' => 'الشروط والاحكام باللغة العربية',
                    'slug_en' => 'Terms And Conditions In Arabic',
                    'value' => 'وريم إيبسوم(Lorem Ipsum) هو ببساطة نص شكلي (بمعنى أن الغاية هي الشكل وليس المحتوى) ويُستخدم في صناعات المطابع ودور النشر. كان لوريم إيبسوم ولايزال المعيار للنص الشكلي منذ القرن الخامس عشر عندما قامت مطبعة مجهولة برص مجموعة من الأحرف بشكل عشوائي أخذتها من نص، لتكوّن كتيّب بمثابة دليل أو مرجع شكلي لهذه الأحرف. خمسة قرون من الزمن لم تقضي على هذا النص، بل انه حتى صار مستخدماً وبشكله الأصلي في الطباعة والتنضيد الإلكتروني. انتشر بشكل كبير في ستينيّات هذا القرن مع إصدار رقائق "ليتراسيت" (Letraset) البلاستيكية تحوي مقاطع من هذا النص، وعاد لينتشر مرة أخرى مؤخراَ مع ظهور برامج النشر الإلكتروني مثل "ألدوس بايج مايكر" (Aldus PageMaker) والتي حوت أيضاً على نسخ من نص لوريم إيبسوم.',
                    'input_type' => 2,
                    'category' => 1,
                    'created_at' => '2020-06-14 18:40:09',
                    'updated_at' => '2020-06-14 18:40:09',
                ),
            55 =>
                array (
                    'id' => 381,
                    'name' => 'policy_en',
                    'slug_ar' => 'الشروط والاحكام باللغة الانجليزية',
                    'slug_en' => 'Terms And Conditions In English',
                    'value' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum',
                    'input_type' => 2,
                    'category' => 1,
                    'created_at' => '2020-06-14 18:40:09',
                    'updated_at' => '2020-06-14 18:40:09',
                ),
            56 =>
                array (
                    'id' => 407,
                    'name' => 'about_ar',
                    'slug_ar' => 'من نحن باللغة العربية',
                    'slug_en' => 'About Us In Arabic',
                    'value' => 'وريم إيبسوم(Lorem Ipsum) هو ببساطة نص شكلي (بمعنى أن الغاية هي الشكل وليس المحتوى) ويُستخدم في صناعات المطابع ودور النشر. كان لوريم إيبسوم ولايزال المعيار للنص الشكلي منذ القرن الخامس عشر عندما قامت مطبعة مجهولة برص مجموعة من الأحرف بشكل عشوائي أخذتها من نص، لتكوّن كتيّب بمثابة دليل أو مرجع شكلي لهذه الأحرف. خمسة قرون من الزمن لم تقضي على هذا النص، بل انه حتى صار مستخدماً وبشكله الأصلي في الطباعة والتنضيد الإلكتروني. انتشر بشكل كبير في ستينيّات هذا القرن مع إصدار رقائق "ليتراسيت" (Letraset) البلاستيكية تحوي مقاطع من هذا النص، وعاد لينتشر مرة أخرى مؤخراَ مع ظهور برامج النشر الإلكتروني مثل "ألدوس بايج مايكر" (Aldus PageMaker) والتي حوت أيضاً على نسخ من نص لوريم إيبسوم.',
                    'input_type' => 2,
                    'category' => 1,
                    'created_at' => '2020-06-14 18:40:20',
                    'updated_at' => '2020-06-14 18:40:20',
                ),
            57 =>
                array (
                    'id' => 408,
                    'name' => 'about_en',
                    'slug_ar' => 'من نحن باللغة الانجليزية',
                    'slug_en' => 'About Us In English',
                    'value' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum',
                    'input_type' => 2,
                    'category' => 1,
                    'created_at' => '2020-06-14 18:40:20',
                    'updated_at' => '2020-06-14 18:40:20',
                ),
            58 =>
                array (
                    'id' => 409,
                    'name' => 'policy_ar',
                    'slug_ar' => 'الشروط والاحكام باللغة العربية',
                    'slug_en' => 'Terms And Conditions In Arabic',
                    'value' => 'وريم إيبسوم(Lorem Ipsum) هو ببساطة نص شكلي (بمعنى أن الغاية هي الشكل وليس المحتوى) ويُستخدم في صناعات المطابع ودور النشر. كان لوريم إيبسوم ولايزال المعيار للنص الشكلي منذ القرن الخامس عشر عندما قامت مطبعة مجهولة برص مجموعة من الأحرف بشكل عشوائي أخذتها من نص، لتكوّن كتيّب بمثابة دليل أو مرجع شكلي لهذه الأحرف. خمسة قرون من الزمن لم تقضي على هذا النص، بل انه حتى صار مستخدماً وبشكله الأصلي في الطباعة والتنضيد الإلكتروني. انتشر بشكل كبير في ستينيّات هذا القرن مع إصدار رقائق "ليتراسيت" (Letraset) البلاستيكية تحوي مقاطع من هذا النص، وعاد لينتشر مرة أخرى مؤخراَ مع ظهور برامج النشر الإلكتروني مثل "ألدوس بايج مايكر" (Aldus PageMaker) والتي حوت أيضاً على نسخ من نص لوريم إيبسوم.',
                    'input_type' => 2,
                    'category' => 1,
                    'created_at' => '2020-06-14 18:40:20',
                    'updated_at' => '2020-06-14 18:40:20',
                ),
            59 =>
                array (
                    'id' => 410,
                    'name' => 'policy_en',
                    'slug_ar' => 'الشروط والاحكام باللغة الانجليزية',
                    'slug_en' => 'Terms And Conditions In English',
                    'value' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum',
                    'input_type' => 2,
                    'category' => 1,
                    'created_at' => '2020-06-14 18:40:20',
                    'updated_at' => '2020-06-14 18:40:20',
                ),
            60 =>
                array (
                    'id' => 436,
                    'name' => 'about_ar',
                    'slug_ar' => 'من نحن باللغة العربية',
                    'slug_en' => 'About Us In Arabic',
                    'value' => 'وريم إيبسوم(Lorem Ipsum) هو ببساطة نص شكلي (بمعنى أن الغاية هي الشكل وليس المحتوى) ويُستخدم في صناعات المطابع ودور النشر. كان لوريم إيبسوم ولايزال المعيار للنص الشكلي منذ القرن الخامس عشر عندما قامت مطبعة مجهولة برص مجموعة من الأحرف بشكل عشوائي أخذتها من نص، لتكوّن كتيّب بمثابة دليل أو مرجع شكلي لهذه الأحرف. خمسة قرون من الزمن لم تقضي على هذا النص، بل انه حتى صار مستخدماً وبشكله الأصلي في الطباعة والتنضيد الإلكتروني. انتشر بشكل كبير في ستينيّات هذا القرن مع إصدار رقائق "ليتراسيت" (Letraset) البلاستيكية تحوي مقاطع من هذا النص، وعاد لينتشر مرة أخرى مؤخراَ مع ظهور برامج النشر الإلكتروني مثل "ألدوس بايج مايكر" (Aldus PageMaker) والتي حوت أيضاً على نسخ من نص لوريم إيبسوم.',
                    'input_type' => 2,
                    'category' => 1,
                    'created_at' => '2020-06-14 18:40:37',
                    'updated_at' => '2020-06-14 18:40:37',
                ),
            61 =>
                array (
                    'id' => 437,
                    'name' => 'about_en',
                    'slug_ar' => 'من نحن باللغة الانجليزية',
                    'slug_en' => 'About Us In English',
                    'value' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum',
                    'input_type' => 2,
                    'category' => 1,
                    'created_at' => '2020-06-14 18:40:37',
                    'updated_at' => '2020-06-14 18:40:37',
                ),
            62 =>
                array (
                    'id' => 438,
                    'name' => 'policy_ar',
                    'slug_ar' => 'الشروط والاحكام باللغة العربية',
                    'slug_en' => 'Terms And Conditions In Arabic',
                    'value' => 'وريم إيبسوم(Lorem Ipsum) هو ببساطة نص شكلي (بمعنى أن الغاية هي الشكل وليس المحتوى) ويُستخدم في صناعات المطابع ودور النشر. كان لوريم إيبسوم ولايزال المعيار للنص الشكلي منذ القرن الخامس عشر عندما قامت مطبعة مجهولة برص مجموعة من الأحرف بشكل عشوائي أخذتها من نص، لتكوّن كتيّب بمثابة دليل أو مرجع شكلي لهذه الأحرف. خمسة قرون من الزمن لم تقضي على هذا النص، بل انه حتى صار مستخدماً وبشكله الأصلي في الطباعة والتنضيد الإلكتروني. انتشر بشكل كبير في ستينيّات هذا القرن مع إصدار رقائق "ليتراسيت" (Letraset) البلاستيكية تحوي مقاطع من هذا النص، وعاد لينتشر مرة أخرى مؤخراَ مع ظهور برامج النشر الإلكتروني مثل "ألدوس بايج مايكر" (Aldus PageMaker) والتي حوت أيضاً على نسخ من نص لوريم إيبسوم.',
                    'input_type' => 2,
                    'category' => 1,
                    'created_at' => '2020-06-14 18:40:37',
                    'updated_at' => '2020-06-14 18:40:37',
                ),
            63 =>
                array (
                    'id' => 439,
                    'name' => 'policy_en',
                    'slug_ar' => 'الشروط والاحكام باللغة الانجليزية',
                    'slug_en' => 'Terms And Conditions In English',
                    'value' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum',
                    'input_type' => 2,
                    'category' => 1,
                    'created_at' => '2020-06-14 18:40:37',
                    'updated_at' => '2020-06-14 18:40:37',
                ),
            64 =>
                array (
                    'id' => 465,
                    'name' => 'about_ar',
                    'slug_ar' => 'من نحن باللغة العربية',
                    'slug_en' => 'About Us In Arabic',
                    'value' => 'وريم إيبسوم(Lorem Ipsum) هو ببساطة نص شكلي (بمعنى أن الغاية هي الشكل وليس المحتوى) ويُستخدم في صناعات المطابع ودور النشر. كان لوريم إيبسوم ولايزال المعيار للنص الشكلي منذ القرن الخامس عشر عندما قامت مطبعة مجهولة برص مجموعة من الأحرف بشكل عشوائي أخذتها من نص، لتكوّن كتيّب بمثابة دليل أو مرجع شكلي لهذه الأحرف. خمسة قرون من الزمن لم تقضي على هذا النص، بل انه حتى صار مستخدماً وبشكله الأصلي في الطباعة والتنضيد الإلكتروني. انتشر بشكل كبير في ستينيّات هذا القرن مع إصدار رقائق "ليتراسيت" (Letraset) البلاستيكية تحوي مقاطع من هذا النص، وعاد لينتشر مرة أخرى مؤخراَ مع ظهور برامج النشر الإلكتروني مثل "ألدوس بايج مايكر" (Aldus PageMaker) والتي حوت أيضاً على نسخ من نص لوريم إيبسوم.',
                    'input_type' => 2,
                    'category' => 1,
                    'created_at' => '2020-06-14 18:40:48',
                    'updated_at' => '2020-06-14 18:40:48',
                ),
            65 =>
                array (
                    'id' => 466,
                    'name' => 'about_en',
                    'slug_ar' => 'من نحن باللغة الانجليزية',
                    'slug_en' => 'About Us In English',
                    'value' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum',
                    'input_type' => 2,
                    'category' => 1,
                    'created_at' => '2020-06-14 18:40:48',
                    'updated_at' => '2020-06-14 18:40:48',
                ),
            66 =>
                array (
                    'id' => 467,
                    'name' => 'policy_ar',
                    'slug_ar' => 'الشروط والاحكام باللغة العربية',
                    'slug_en' => 'Terms And Conditions In Arabic',
                    'value' => 'وريم إيبسوم(Lorem Ipsum) هو ببساطة نص شكلي (بمعنى أن الغاية هي الشكل وليس المحتوى) ويُستخدم في صناعات المطابع ودور النشر. كان لوريم إيبسوم ولايزال المعيار للنص الشكلي منذ القرن الخامس عشر عندما قامت مطبعة مجهولة برص مجموعة من الأحرف بشكل عشوائي أخذتها من نص، لتكوّن كتيّب بمثابة دليل أو مرجع شكلي لهذه الأحرف. خمسة قرون من الزمن لم تقضي على هذا النص، بل انه حتى صار مستخدماً وبشكله الأصلي في الطباعة والتنضيد الإلكتروني. انتشر بشكل كبير في ستينيّات هذا القرن مع إصدار رقائق "ليتراسيت" (Letraset) البلاستيكية تحوي مقاطع من هذا النص، وعاد لينتشر مرة أخرى مؤخراَ مع ظهور برامج النشر الإلكتروني مثل "ألدوس بايج مايكر" (Aldus PageMaker) والتي حوت أيضاً على نسخ من نص لوريم إيبسوم.',
                    'input_type' => 2,
                    'category' => 1,
                    'created_at' => '2020-06-14 18:40:48',
                    'updated_at' => '2020-06-14 18:40:48',
                ),
            67 =>
                array (
                    'id' => 468,
                    'name' => 'policy_en',
                    'slug_ar' => 'الشروط والاحكام باللغة الانجليزية',
                    'slug_en' => 'Terms And Conditions In English',
                    'value' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum',
                    'input_type' => 2,
                    'category' => 1,
                    'created_at' => '2020-06-14 18:40:48',
                    'updated_at' => '2020-06-14 18:40:48',
                ),
            68 =>
                array (
                    'id' => 469,
                    'name' => 'vision_ar',
                    'slug_ar' => 'رويتنا بالعربية',
                    'slug_en' => 'our vision in arabic',
                    'value' => ' when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
                    'input_type' => 2,
                    'category' => 2,
                    'created_at' => '2020-06-14 18:40:49',
                    'updated_at' => '2020-06-14 18:40:49',
                ),
            69 =>
                array (
                    'id' => 470,
                    'name' => 'goal_ar',
                    'slug_ar' => 'هدفنا بالعربية',
                    'slug_en' => 'our goal in arabic',
                    'value' => 'when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
                    'input_type' => 2,
                    'category' => 2,
                    'created_at' => '2020-06-14 18:40:49',
                    'updated_at' => '2020-06-14 18:40:49',
                ),
            70 =>
                array (
                    'id' => 471,
                    'name' => 'idea_ar',
                    'slug_ar' => 'فكرتنا بالعربية',
                    'slug_en' => 'our idea in arabic',
                    'value' => 'when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
                    'input_type' => 2,
                    'category' => 2,
                    'created_at' => '2020-06-14 18:40:49',
                    'updated_at' => '2020-06-14 18:40:49',
                ),
            71 =>
                array (
                    'id' => 472,
                    'name' => 'vision_en',
                    'slug_ar' => 'ؤويتنا بالانجليزية',
                    'slug_en' => 'our vision in english',
                    'value' => ' when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
                    'input_type' => 2,
                    'category' => 2,
                    'created_at' => '2020-06-14 18:40:49',
                    'updated_at' => '2020-06-14 18:40:49',
                ),
            72 =>
                array (
                    'id' => 473,
                    'name' => 'goal_en',
                    'slug_ar' => 'هدفنا بالانجليزية',
                    'slug_en' => 'our goal in english',
                    'value' => 'when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
                    'input_type' => 2,
                    'category' => 2,
                    'created_at' => '2020-06-14 18:40:49',
                    'updated_at' => '2020-06-14 18:40:49',
                ),
            73 =>
                array (
                    'id' => 474,
                    'name' => 'why_us_en',
                    'slug_ar' => 'لماذا نحن بالانجليزية',
                    'slug_en' => 'why us in english',
                    'value' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop p',
                    'input_type' => 2,
                    'category' => 2,
                    'created_at' => '2020-06-14 18:40:49',
                    'updated_at' => '2020-06-14 18:40:49',
                ),
            74 =>
                array (
                    'id' => 475,
                    'name' => 'why_us_ar',
                    'slug_ar' => 'لماذا نحن بالعربية',
                    'slug_en' => 'why us in english',
                    'value' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop p',
                    'input_type' => 2,
                    'category' => 2,
                    'created_at' => '2020-06-14 18:40:49',
                    'updated_at' => '2020-06-14 18:40:49',
                ),
            75 =>
                array (
                    'id' => 476,
                    'name' => 'idea_en',
                    'slug_ar' => 'فكرتنا بالانجليزية',
                    'slug_en' => 'our idea in english',
                    'value' => 'when an unknown printer took a galley of type and scrambled it to make a type specimen book.',
                    'input_type' => 2,
                    'category' => 2,
                    'created_at' => '2020-06-14 18:40:49',
                    'updated_at' => '2020-06-14 18:40:49',
                ),
            76 =>
                array (
                    'id' => 477,
                    'name' => 'search_box_en',
                    'slug_ar' => 'نص ابحث بالانجليزية',
                    'slug_en' => 'Search Box Text in english',
                    'value' => 'By speciatilty doctor name or fees',
                    'input_type' => 0,
                    'category' => 2,
                    'created_at' => '2020-06-14 18:40:49',
                    'updated_at' => '2020-06-14 18:40:49',
                ),
            77 =>
                array (
                    'id' => 478,
                    'name' => 'search_box_ar',
                    'slug_ar' => 'نص ابحث بالعربية',
                    'slug_en' => 'Search Box Text in arabic',
                    'value' => 'By speciatilty doctor name or fees',
                    'input_type' => 0,
                    'category' => 2,
                    'created_at' => '2020-06-14 18:40:49',
                    'updated_at' => '2020-06-14 18:40:49',
                ),
            78 =>
                array (
                    'id' => 479,
                    'name' => 'compare_box_en',
                    'slug_ar' => 'نص قارن واخنار بالانجليزية',
                    'slug_en' => 'Compare & Choose Box Text in english',
                    'value' => 'Based on real patients reviews',
                    'input_type' => 0,
                    'category' => 2,
                    'created_at' => '2020-06-14 18:40:49',
                    'updated_at' => '2020-06-14 18:40:49',
                ),
            79 =>
                array (
                    'id' => 480,
                    'name' => 'compare_box_ar',
                    'slug_ar' => ' قارن و احتار بالعربية',
                    'slug_en' => 'Compare & Choose Text in arabic',
                    'value' => 'Based on real patients reviews',
                    'input_type' => 0,
                    'category' => 2,
                    'created_at' => '2020-06-14 18:40:49',
                    'updated_at' => '2020-06-14 18:40:49',
                ),
            80 =>
                array (
                    'id' => 481,
                    'name' => 'book_box_en',
                    'slug_ar' => ' نص احجز الان بالانجليزية',
                    'slug_en' => 'Booking Box Text in english',
                    'value' => 'pay at the clinic at no extra cost',
                    'input_type' => 0,
                    'category' => 2,
                    'created_at' => '2020-06-14 18:40:49',
                    'updated_at' => '2020-06-14 18:40:49',
                ),
            81 =>
                array (
                    'id' => 482,
                    'name' => 'book_box_ar',
                    'slug_ar' => ' نص احجز الان بالعربية',
                    'slug_en' => 'Booking Box Text in arabic',
                    'value' => 'pay at the clinic at no extra cost',
                    'input_type' => 0,
                    'category' => 2,
                    'created_at' => '2020-06-14 18:40:49',
                    'updated_at' => '2020-06-14 18:40:49',
                ),
            82 =>
                array (
                    'id' => 483,
                    'name' => 'download_description_ar',
                    'slug_ar' => 'نص تحميل الابلكشن بالعربية',
                    'slug_en' => 'Download App Description in arabic',
                    'value' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
                    'input_type' => 2,
                    'category' => 2,
                    'created_at' => '2020-06-14 18:40:49',
                    'updated_at' => '2020-06-14 18:40:49',
                ),
            83 =>
                array (
                    'id' => 484,
                    'name' => 'download_description_en',
                    'slug_ar' => 'نص تحميل الابلكشن بالعربية',
                    'slug_en' => 'Download App Description in english',
                    'value' => 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
                    'input_type' => 2,
                    'category' => 2,
                    'created_at' => '2020-06-14 18:40:49',
                    'updated_at' => '2020-06-14 18:40:49',
                ),
            84 =>
                array (
                    'id' => 485,
                    'name' => 'andriod_link',
                    'slug_ar' => 'رابط التحميل من جوجل بلاى',
                    'slug_en' => ' App Google Play Link',
                    'value' => '#',
                    'input_type' => 0,
                    'category' => 2,
                    'created_at' => '2020-06-14 18:40:49',
                    'updated_at' => '2020-06-14 18:40:49',
                ),
            85 =>
                array (
                    'id' => 486,
                    'name' => 'ios_link',
                    'slug_ar' => 'رابط التحميل من بلاى ستور',
                    'slug_en' => ' App Play Store Link',
                    'value' => '#',
                    'input_type' => 0,
                    'category' => 2,
                    'created_at' => '2020-06-14 18:40:49',
                    'updated_at' => '2020-06-14 18:40:49',
                ),
            86 =>
                array (
                    'id' => 487,
                    'name' => 'facebook Link',
                    'slug_ar' => 'رابط الفيسبوك',
                    'slug_en' => 'Facebook Link',
                    'value' => '#',
                    'input_type' => 0,
                    'category' => 3,
                    'created_at' => '2020-06-14 18:40:49',
                    'updated_at' => '2020-06-14 18:40:49',
                ),
            87 =>
                array (
                    'id' => 488,
                    'name' => 'twitter Link',
                    'slug_ar' => 'رابط تويتر',
                    'slug_en' => 'twitter  Link',
                    'value' => '#',
                    'input_type' => 0,
                    'category' => 3,
                    'created_at' => '2020-06-14 18:40:49',
                    'updated_at' => '2020-06-14 18:40:49',
                ),
            88 =>
                array (
                    'id' => 489,
                    'name' => 'snapchat Link',
                    'slug_ar' => 'رابط سناب شات',
                    'slug_en' => 'snapchat Link',
                    'value' => '#',
                    'input_type' => 0,
                    'category' => 3,
                    'created_at' => '2020-06-14 18:40:49',
                    'updated_at' => '2020-06-14 18:40:49',
                ),
            89 =>
                array (
                    'id' => 490,
                    'name' => 'address_ar',
                    'slug_ar' => 'العنوان باللغة العربية',
                    'slug_en' => 'Address in Arabic',
                    'value' => 'Saudi Arabia - Makkah - 122 Block',
                    'input_type' => 0,
                    'category' => 4,
                    'created_at' => '2020-06-14 18:40:49',
                    'updated_at' => '2020-06-14 18:40:49',
                ),
            90 =>
                array (
                    'id' => 491,
                    'name' => 'address_en',
                    'slug_ar' => 'العنوان باللغة الانجليزية',
                    'slug_en' => 'Address in English',
                    'value' => 'Saudi Arabia - Makkah - 122 Block',
                    'input_type' => 0,
                    'category' => 4,
                    'created_at' => '2020-06-14 18:40:49',
                    'updated_at' => '2020-06-14 18:40:49',
                ),
            91 =>
                array (
                    'id' => 492,
                    'name' => 'phone 1',
                    'slug_ar' => 'رقم الهاتف 1',
                    'slug_en' => 'Phone Number 1',
                    'value' => '0000000000000',
                    'input_type' => 0,
                    'category' => 4,
                    'created_at' => '2020-06-14 18:40:49',
                    'updated_at' => '2020-06-14 18:40:49',
                ),
            92 =>
                array (
                    'id' => 493,
                    'name' => 'phone 2',
                    'slug_ar' => 'رقم الهاتف 2',
                    'slug_en' => 'Phone Number 2',
                    'value' => '0000000000000',
                    'input_type' => 0,
                    'category' => 4,
                    'created_at' => '2020-06-14 18:40:49',
                    'updated_at' => '2020-06-14 18:40:49',
                ),
        ));


    }

}
